version: 2
updates:
- package-ecosystem: "nuget"
  directory: "/templates/anvil/plugin/"
  schedule:
    interval: daily
- package-ecosystem: "nuget"
  directory: "/templates/anvil/service/"
  schedule:
    interval: daily
